name: Debug Linux Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # ----------------------------
    # LINUX DEPENDENCIES
    # ----------------------------
    - name: Install dependencies
      run: |
        sudo apt update
        # Installing deps required for static linking (ICU, ZSTD, etc)
        sudo apt install -y cmake g++ wget libzstd-dev libbz2-dev zlib1g-dev pkg-config libicu-dev
        
        # Manual Boost 1.89 install
        cd /tmp
        wget https://github.com/boostorg/boost/releases/download/boost-1.89.0/boost-1.89.0-cmake.tar.gz
        tar xzf boost-1.89.0-cmake.tar.gz
        cd boost-1.89.0
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=OFF
        sudo cmake --build . --target install -j$(nproc)

    # ----------------------------
    # BUILD
    # ----------------------------
    - name: Build
      run: |
        mkdir build
        cd build
        # CMake config for Linux
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DBoost_USE_STATIC_LIBS=ON
        cmake --build . --parallel

    # ----------------------------
    # SAVE ARTIFACTS
    # ----------------------------
    - name: Stage Binaries
      run: |
        mkdir dist
        cp build/progressiveMauve dist/
        cp build/mauveAligner dist/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: progressiveMauve-Linux-Debug
        path: dist/*
